# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.cache/wt} [current_project]
set_property parent.project_path {C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo {c:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet {{c:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1/clk_wiz_1.dcp}}
set_property used_in_implementation false [get_files {{c:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1/clk_wiz_1.dcp}}]
read_verilog -library xil_defaultlib {
  {C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/new/top.v}
  {C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/new/display.v}
  {C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/new/game.v}
  {C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/new/two_7seg.v}
  {C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/new/iclk_gen.v}
  {C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/new/spi_master.v}
}
read_ip -quiet {{C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/vga_game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/sources/NexysA7-100t.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/ZeroX/Documents/CECS 361 PONG PROJECT/VerilogPong/sources/NexysA7-100t.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
